services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: perla
      POSTGRES_PASSWORD: piwo
      POSTGRES_DB: egarage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: